# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: convertor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='convertor.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0f\x63onvertor.proto\"[\n\x16LengthConvertorRequest\x12\x19\n\x04\x66rom\x18\x01 \x01(\x0e\x32\x0b.LengthUnit\x12\x17\n\x02to\x18\x02 \x01(\x0e\x32\x0b.LengthUnit\x12\r\n\x05value\x18\x03 \x01(\x01\"(\n\x17LengthConvertorResponse\x12\r\n\x05value\x18\x01 \x01(\x01*%\n\nLengthUnit\x12\r\n\tKILOMETRE\x10\x00\x12\x08\n\x04YARD\x10\x01\x32O\n\tConvertor\x12\x42\n\rConvertLength\x12\x17.LengthConvertorRequest\x1a\x18.LengthConvertorResponseb\x06proto3')
)

_LENGTHUNIT = _descriptor.EnumDescriptor(
  name='LengthUnit',
  full_name='LengthUnit',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KILOMETRE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='YARD', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=154,
  serialized_end=191,
)
_sym_db.RegisterEnumDescriptor(_LENGTHUNIT)

LengthUnit = enum_type_wrapper.EnumTypeWrapper(_LENGTHUNIT)
KILOMETRE = 0
YARD = 1



_LENGTHCONVERTORREQUEST = _descriptor.Descriptor(
  name='LengthConvertorRequest',
  full_name='LengthConvertorRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from', full_name='LengthConvertorRequest.from', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='to', full_name='LengthConvertorRequest.to', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='LengthConvertorRequest.value', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=110,
)


_LENGTHCONVERTORRESPONSE = _descriptor.Descriptor(
  name='LengthConvertorResponse',
  full_name='LengthConvertorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='LengthConvertorResponse.value', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=152,
)

_LENGTHCONVERTORREQUEST.fields_by_name['from'].enum_type = _LENGTHUNIT
_LENGTHCONVERTORREQUEST.fields_by_name['to'].enum_type = _LENGTHUNIT
DESCRIPTOR.message_types_by_name['LengthConvertorRequest'] = _LENGTHCONVERTORREQUEST
DESCRIPTOR.message_types_by_name['LengthConvertorResponse'] = _LENGTHCONVERTORRESPONSE
DESCRIPTOR.enum_types_by_name['LengthUnit'] = _LENGTHUNIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LengthConvertorRequest = _reflection.GeneratedProtocolMessageType('LengthConvertorRequest', (_message.Message,), {
  'DESCRIPTOR' : _LENGTHCONVERTORREQUEST,
  '__module__' : 'convertor_pb2'
  # @@protoc_insertion_point(class_scope:LengthConvertorRequest)
  })
_sym_db.RegisterMessage(LengthConvertorRequest)

LengthConvertorResponse = _reflection.GeneratedProtocolMessageType('LengthConvertorResponse', (_message.Message,), {
  'DESCRIPTOR' : _LENGTHCONVERTORRESPONSE,
  '__module__' : 'convertor_pb2'
  # @@protoc_insertion_point(class_scope:LengthConvertorResponse)
  })
_sym_db.RegisterMessage(LengthConvertorResponse)



_CONVERTOR = _descriptor.ServiceDescriptor(
  name='Convertor',
  full_name='Convertor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=193,
  serialized_end=272,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertLength',
    full_name='Convertor.ConvertLength',
    index=0,
    containing_service=None,
    input_type=_LENGTHCONVERTORREQUEST,
    output_type=_LENGTHCONVERTORRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONVERTOR)

DESCRIPTOR.services_by_name['Convertor'] = _CONVERTOR

# @@protoc_insertion_point(module_scope)
