# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import convertor_pb2 as convertor__pb2


class ConvertorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ConvertLength = channel.unary_unary(
        '/Convertor/ConvertLength',
        request_serializer=convertor__pb2.LengthConvertorRequest.SerializeToString,
        response_deserializer=convertor__pb2.LengthConvertorResponse.FromString,
        )


class ConvertorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ConvertLength(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ConvertorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ConvertLength': grpc.unary_unary_rpc_method_handler(
          servicer.ConvertLength,
          request_deserializer=convertor__pb2.LengthConvertorRequest.FromString,
          response_serializer=convertor__pb2.LengthConvertorResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Convertor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
